---
title: "Useful links and materials"
---
  
__Modeling for SSAs__  
  
[Conceptual diagram](static/handouts/conceptual-diagram.pdf)  
  
---
  
__Species Status Assessments__  
  
[SSA process overview](static/handouts/Smith_etal_2018_SSA.pdf)  
  
[Sonoran desert tortoise SSA case study](McGowan_etal_2017_SDTSSA.pdf)
  
---
  
__General__  
  
[Best practices for spreadsheets](static/handouts/Broman-Woo-2018.pdf)
  
[Guide to statistical distributions](static/handouts/distributions.pdf) 
  
---
  
__Species Distribution Models__  
  
[SDMs for Conservation Educators and Practioners](static/handouts/SDMs-for-educators-and-practitioners.pdf)  
  
---
  
__Recommended Reading__  
  
[The Signal and the Noise: Why So Many Predictions Fail--but Some Don't](https://www.amazon.com/Signal-Noise-Many-Predictions-Fail-but-ebook/dp/B007V65R54)   
Drawing on his own groundbreaking work, Silver examines the world of prediction, investigating how we can distinguish a true signal from a universe of noisy data. Most predictions fail, often at great cost to society, because most of us have a poor understanding of probability and uncertainty. Both experts and laypeople mistake more confident predictions for more accurate ones. But overconfidence is often the reason for failure. If our appreciation of uncertainty improves, our predictions can get better too. This is the “prediction paradox”: The more humility we have about our ability to make predictions, the more successful we can be in planning for the future.  
  
  
[Quantitative Conservation Biology: Theory and Practice of Population Viability Analysis](https://www.amazon.com/Quantitative-Conservation-Biology-Population-Viability/dp/0878935460)   
The goal of this book is to provide practical, intelligible, and intuitive explanations of population modeling to empirical ecologists and conservation biologists. Modeling methods that do not require large amounts of data (typically unavailable for endangered species) are emphasized. As such, the book is appropriate for undergraduate and graduate students interested in quantitative conservation biology, managers charged with preserving endangered species, and, in short, for any conservation biologist or ecologist seeking to better understand the analysis and modeling of population data.  
  
---  
  
__Exploring probability and uncertainty__  
  
[Another Shiny app!](https://amtucker.shinyapps.io/wild4890_pva/)  
This app allows you to explore the effects of incoporating different types of uncertainties into population size projections using lambda and/or intrinsic rate of increase.  
  
[A visual introduction to probability and statistics](https://seeing-theory.brown.edu/)   
This is a very cool set of modules to introduce basic concepts in probability and statistics using interactive visuals. Highly recommended!  
   
---  
  
__Demographic matrix models__  
[COMADRE and COMPADRE Databases](https://comadre-db.org/)  
This is a freely-available database where the authors have compiled estimates of demographic rates from published studies of plants (COMPADRE) and animals (COMADRE). There is demographic information from 405 animals and 695 plants in the database currently, with the majority from N. America. This could be a great resource for demographic estimates of sister taxa.  
  
